
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  const avfallsTyperWP = await fetch('https://reklameservice.no/wp-json/wp/v2/avfallstyper?acf_format=standard');
  const avfallsTyperData = await avfallsTyperWP.json();
  const avfallsTyper = avfallsTyperData;

  const skjermerWP = await fetch('https://reklameservice.no/wp-json/wp/v2/rir?acf_format=standard');
  const skjermerData = await skjermerWP.json();

  const skjerm7Data = skjermerData.find(skjerm => skjerm.id === 104696);
  const skjerm7 = skjerm7Data.acf.innhold.ID;
  const skjerm7ID = avfallsTyper.find(innhold => innhold.id === skjerm7);
  const skjerm7Innhold = skjerm7ID.acf;

  const skjerm8Data = skjermerData.find(skjerm => skjerm.id === 104697);
  const skjerm8 = skjerm8Data.acf.innhold.ID;
  const skjerm8ID = avfallsTyper.find(innhold => innhold.id === skjerm8);
  const skjerm8Innhold = skjerm8ID.acf;

  const skjerm9Data = skjermerData.find(skjerm => skjerm.id === 104698);
  const skjerm9 = skjerm9Data.acf.innhold.ID;
  const skjerm9ID = avfallsTyper.find(innhold => innhold.id === skjerm9);
  const skjerm9Innhold = skjerm9ID.acf;

  const skjerm10Data = skjermerData.find(skjerm => skjerm.id === 104699);
  const skjerm10 = skjerm10Data.acf.innhold.ID;
  const skjerm10ID = avfallsTyper.find(innhold => innhold.id === skjerm10);
  const skjerm10Innhold = skjerm10ID.acf;

  console.log(skjerm10Innhold);


  return {
    props: {
      skjerm7: skjerm7Innhold,
      skjerm8: skjerm8Innhold,
      skjerm9: skjerm9Innhold,
      skjerm10: skjerm10Innhold,
    },
    revalidate: 1,
  }
}

export default function Home( skjerm7, skjerm8 ) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className='grid order-2 xl:order-3 justify-center items-center grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5 p-5 md:gap-10 md:p-10 uppercase'>
      {Object.values(skjerm7).map(post => (
        <div className=' bg-white' key={post.id}>
          <img src={post.ikon} width={200} height={200}/>
          <div>{post.tekst}</div>
        </div>
      ))}
      {Object.values(skjerm8).map(post => (
        <div className=' bg-white' key={post.id}>
          <img src={post.ikon} width={200} height={200}/>
          <div>{post.tekst}</div>
        </div>
      ))}
      </div>
      </main>
    </>
  )
}
